---
- hosts: localhost
  become: yes
  tasks:
  - name: Create Ansible Nodes
    ec2:
      aws_access_key: AKIAWTPYBXESAYELST4H
      aws_secret_access_key: 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
      key_name: sriluawskey
      instance_type: t2.micro
      image: ami-00aa96edc56b79d70
      wait: yes
      region: us-east-2
      group: launch-wizard-3
      count: 2
      vpc_subnet_id: subnet-39692943
      assign_public_ip: yes
      instance_tags:
        name: AnsibleNodes