---
- hosts: webserver
  become: yes
  tasks:
  - name: Install git on Ubuntu
    apt: 
      name: git

  - name: Install tree on Ubuntu
    apt:
      namee: tree
    ignore_errors: yes
  
  - name: install wget
    apt:
      name: wget