---
- hosts: all
  become: yes
  tasks:
  - name: Install webserver on ubuntu16
    apt:
      name: apache2
      state: present

  - name: Start the webserver on ubuntu16
    service:
      name: apache2
      state: started