---
- hosts: webserver
  become: yes
  tasks:
  - name: Getting hostname
    command: hostname -f
    register: myresult

  - name: Display hostname
    debug:
      msg: "{{myresult}}"

  - name: Install git
    apt:
     name: git
     state: present
    when: myresult.stderr == ""

  - name: Install tree
    apt:
     name: tree
     state: present
    when: myresult.stderr != ""
