---
# tasks file for webrole2
- name: Install Tomcat7
  apt:
    name: Tomcat7
    state: present

- name: Copy tomcat config file into tom nodes
  template:
    src: templates/myconfig.j2
    dest: /etc/default/tomcat7
  notify: restarttomcat

- name: Install admin packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - tomcat7-docs
    - tomcat7-admin
    - tomcat7-examples
  
- name: Copy tom user file to nodes
  template:
    src: templates/mytomuser.j2
    dest: /etc/tomcat7/tomcat-users.xml
  notify: restarttomcat

- name: Deploy Java Application
  get_url:
    url: https://maha1234.s3-us-west-2.amazonaws.com/mahaLogin.war
    dest: /var/lib/tomcat7/webapps/mahaLogin.war
    force_basic_auth: yes 

    