---
# tasks file for webrole
- name: Install werserver on Ubuntu16
  apt: 
    name: apache2
    state: present
  notify: restartwebserver

- name: Install Webserver on Redhat
  yum:
    name: httpd
    state: present
  notify: restarthttpd